baseurl = "/"
languageCode = "en-us"
title = "TEDxACCD | Coming Soon"

[params]
  author = "TEDxACCD"
  description = "TEDxACCD is an independently organized TED event. The talk aims to connect ideas and emerging patterns across disciplines. Event is coming soon to ArtCenter College of Design this fall."
