
baseurl = "/"
languageCode = "en-us"
title = "TEDxACCD 2017"
enableRobotsTXT = true

[params]
  author = "TEDxACCD"
  description = "TEDxACCD is an independently organized TED event. The talk aims to connect ideas and emerging patterns across disciplines. Event is coming soon to ArtCenter College of Design on November 4th."

  [params.index]
    heading = "Beauty of<br/>the <span class='ani-glitch' data-text='Fail'>Fall</span>"
    date = "November 04, 2017"
    location = "ArtCenter College of Design"

    [[params.index.section]]
      heading = "Thought provoking experience"
      body = "TEDxACCD is a bi-annual event uniquely led by students to create passionate conversations within the community by sharing and spreading ideas intersecting in technology, entertainment, and design."
      cta = "Get Tickets"
      url = "https://engage.artcenter.edu/2017-tedxaccd"
      section = "content--secondary"

    [[params.index.section]]
      heading = "Inspire, encourage and catalyze"
      body = "We invited a group of visionaries, game-changers, innovators, creatives, learners, and mentors to share their unique insights and ideas on failure."
      cta = "View Speakers"
      url = "/speakers"

  [params.about]
    heading = "What to expect"

    [[params.about.section]]
      heading = "Summary"
      body = "On November 4th, join us to hear 12 unique and diverse topics related to failure. The day will be broken into 3 sessions filled in-between with interactive booths and activities. Lunch and snacks will be provided followed by a reception."
      cta = ""
      url = ""

    [[params.about.section]]
      heading = "The theme"
      body = "Failure is an inherent and fundamental experience of life. As human beings, we walk blindly into the world, striving to satisfy our needs, passions, and dreams although our fulfillment is not guaranteed. However, failure is a purifying process that strips away the inessential, revealing our inner selves and utmost potential. Do you dare to fail?"
      cta = ""

    [[params.about.section]]
      heading = "About TEDx"
      body = "In the spirit of ideas worth spreading, TEDx is a program of local, self-organized events that bring people together to share a TED-like experience. At a TEDx event, TED Talks video and live speakers combine to spark deep discussion and connection. These local, self-organized events are branded TEDx, where x = independently organized TED event. The TED Conference provides general guidance for the TEDx program, but individual TEDx events are self-organized. (Subject to certain rules and regulations.)"
      cta = ""

  [params.venue]
    heading = "Venue and parking"

    [[params.venue.section]]
      heading = "About ArtCenter"
      section = "ArtCenter College of Design is located on the iconic Hillside Campus in Pasadena, Ca. For more than 80 years ArtCenter has trained generations of artists and designers all around the globe who are creating influential change in their fields of advertising, entertainment design, environmental design, photography, film, fine art, graphic design, illustration, interaction design, product design, and transportation design.<br/><br/>Being the first design school to receive international certification as a Non-Governmental Organization (NGO) by the United Nations, ArtCenter is leading a new generation of designers to think about design and its impact in people’s lives."
      address = "ArtCenter Hillside Campus<br/>1700 Lida Street<br/>Pasadena, CA 91103"
      map = "true"

    [[params.venue.section]]
      heading = "Parking"
      section = "ArtCenter will provide free on-campus parking to all attendees.<br/><br/>All attendees will be able to park in the North Lot at Hillside Campus as directed by Security.<br/><br/>All stakeholders, sponsors, and speakers will receive special parking information before the event."
      address = ""

  [params.speaker]
    heading = "Stories from diverse fields"

  [params.team]
    heading = "Creatives challenging the norm"

  [params.partner]
    heading = "Partner<br/>with us"

    [params.partner.become]
      heading = "Become a partner"
      body = "We welcome you and your company to partner and join the TEDxACCD family. Our student committees goal is to cover all costs for our event and assure the same quality of excellence in future TEDxACCD events. We seek to raise both financial and in-kind sponsorship. Come and be a part of this experience by becoming a TEDxACCD sponsor. Your contribution will help not only this year's team but also the dreams of future TEDxACCD student leaders."
      role = "Sponsorship Coordinator"
      contact = "Sophia de Lara"
      email = "sophia@tedxaccd.com"
      
    [[params.partner.gold]]
      name = "Sodexo"
      logo = "sodexo.png"
      url = "http://www.sodexousa.com/"
      host = "sodexousa.com"
      
    [[params.partner.gold]]
      name = "Full Circle"
      logo = "fullcircle.png"
      url = "http://www.artcenter.edu/about/support/fullcircle.html"
      host = "artcenter.edu"
      
    [[params.partner.silver]]
      name = "H.M.C.T."
      logo = "hmct.png"
      url = "http://hmctartcenter.org/"
      host = "hmctartcenter.org"
      
    [[params.partner.silver]]
      name = "Idealab"
      logo = "idealab.png"
      url = "https://www.idealab.com/"
      host = "idealab.com"
      
    [[params.partner.silver]]
      name = "David Martin"
      logo = "david.png"
      url = "#"
      
  [params.schedule]
    heading = "Schedule"
    
    [[params.schedule.section]]
      heading = "Saturday, November 4th"
      body = ""
    
    [[params.schedule.session]]
      heading = "Registration"
      
      [[params.schedule.session.slot]]
        time = "09:00 AM"
        heading = "Check-in"
        body = "Breakfast and coffee provided. Sign up for Junk Battle during Lunch"
        slug = ""
        
      [[params.schedule.session.slot]]
        time = "09:30 AM"
        heading = "Doors Open"
        body = "The Ahmanson Auditorium open for all guests to seat"
        slug = ""
        
    [[params.schedule.session]]
      heading = "Session One"
      
      [[params.schedule.session.slot]]
        time = "10:00 AM"
        heading = "Event Introduction"
        body = "A word from the organizers"
        slug = ""
        
      [[params.schedule.session.slot]]
        time = "10:10 AM"
        heading = "Bruce Heavin"
        body = "Co-Founder of Lynda.com, ArtCenter Board of Trustees"
        slug = "bruce-heavin"
        
      [[params.schedule.session.slot]]
        time = "10:30 AM"
        heading = "Shirin Hashem"
        body = "Fashion Consultant and Special Events Producer"
        slug = "shirin-hashem"
      
      [[params.schedule.session.slot]]
        time = "10:50 AM"
        heading = "Sara Ortloff Khoury"
        body = "Director of User Experience Design at Google"
        slug = "sara-khoury"
        
      [[params.schedule.session.slot]]
        time = "11:10 AM"
        heading = "Akuyoe Graham"
        body = "Awardwinning Playwright, Actor, and Educator"
        slug = "akuyoe-graham"
        
    [[params.schedule.session]]
      heading = "Lunch"
      
      [[params.schedule.session.slot]]
        time = "11:35 AM – 12:30 PM"
        heading = "Lunch Break"
        body = ""
        slug = ""
        
      [[params.schedule.session.slot]]
        time = "11:35 AM"
        heading = "Junk Battle"
        body = "In partnership with Junk Lab, guests will upcycle furniture with ArtCenter’s waste stream."
        slug = ""
        
    [[params.schedule.session]]
      heading = "Session Two"
      
      [[params.schedule.session.slot]]
        time = "12:35 PM"
        heading = "TED Video"
        body = "An official, pre-recorded TED Talk will be featured"
        slug = ""
        
      [[params.schedule.session.slot]]
        time = "12:55 PM"
        heading = "Word from Fred Fehlau"
        body = "A quick message from our provost at ArtCenter"
        slug = ""
        
      [[params.schedule.session.slot]]
        time = "01:00 PM"
        heading = "Alan Castel"
        body = "Professor of Psychology at UCLA"
        slug = "alan-castel"
      
      [[params.schedule.session.slot]]
        time = "01:20 PM"
        heading = "Tracy Drain"
        body = "Systems Engineer at JPL"
        slug = "tracy-drain"
        
      [[params.schedule.session.slot]]
        time = "01:40 PM"
        heading = "Mary Sue Milliken"
        body = "Chef, Restraunteur, Author, TV Personality"
        slug = "mary-milliken"
        
      [[params.schedule.session.slot]]
        time = "02:00 PM"
        heading = "AB Cassidy"
        body = "Comedian, Writer, and Actor"
        slug = "ab-cassidy"
        
  [[params.schedule.session]]
    heading = "Break"
    
    [[params.schedule.session.slot]]
      time = "02:30 PM – 03:30 PM"
      heading = "Break"
      body = "Enjoy a chat with everyone else around you. Snacks provided"
      slug = ""
      
  [[params.schedule.session]]
    heading = "Session Three"
    
    [[params.schedule.session.slot]]
      time = "03:35 PM"
      heading = "TED Video"
      body = "An official, pre-recorded TED Talk will be featured"
      slug = ""
      
    [[params.schedule.session.slot]]
      time = "03:55 PM"
      heading = "Jasmine Henderson"
      body = "Professional Soccer Player, World Record Holder, Motivational Speaker, and Author"
      slug = "jasmine-henderson"
    
    [[params.schedule.session.slot]]
      time = "04:15 PM"
      heading = "Noah Minuskin"
      body = "Tattoo Artist, Business Owner, ArtCenter Illustration Alum"
      slug = "noah-minuskin"
      
    [[params.schedule.session.slot]]
      time = "04:35 PM"
      heading = "Story Musgrave"
      body = "Astronaut, Physician, Scientist, Teacher, Mentor, and much more"
      slug = "story-musgrave"
      
    [[params.schedule.session.slot]]
      time = "04:55 PM"
      heading = "Charlie Hodges"
      body = "Professional Dancer; Product Design Student at ArtCenter"
      slug = "charlie-hodges"
      
    [[params.schedule.session.slot]]
      time = "05:15 PM"
      heading = "Closing Remarks"
      body = ""
      slug = ""
      
  [[params.schedule.session]]
    heading = "Reception"
    
    [[params.schedule.session.slot]]
      time = "05:30 PM – 8:00 PM"
      heading = "Reception"
      body = "Small bites and alcohol will be provided"
      slug = ""
      
    [[params.schedule.session.slot]]
      time = "05:30 PM"
      heading = "Live Performance: Ready Player Two"
      body = "Featuring Jericho Law, London Pearson, Jean Lee, and David Lee"
      slug = ""
      
    [[params.schedule.session.slot]]
      time = "06:30 PM"
      heading = "Live Performance: One Step Closer"
      body = "Featuring Miky Tayoba and Estefania Padilla"
      slug = ""

  [params.footer]
    [[params.footer.social]]
      name = "Facebook"
      url = "//www.facebook.com/tedxaccd"

    [[params.footer.social]]
      name = "Instagram"
      url = "//www.instagram.com/tedxaccd"

    [[params.footer.social]]
      name = "Twitter"
      url = "//twitter.com/tedxaccd"

    [[params.footer.links]]
      name = "Privacy"
      url = "/privacy/"

    [[params.footer.links]]
      name = "Terms & Conditions"
      url = "/terms/"

    [[params.footer.links]]
      name = "Contact"
      url = "mailto:info@tedxaccd.com"
