baseurl = "/"
languageCode = "en-us"
title = "TEDx is Back - TEDxACCD"

[params]
  author = "TEDxACCD"
  description = "TEDxACCD is an independently organized TED event. The talk aims to connect ideas and emerging patterns across disciplines. The event is coming soon to ArtCenter College of Design this fall."
